<<<<<<< HEAD

=======
>>>>>>> 350310163d4012edafe35ba605a67c98a01052b7
changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
<<<<<<< HEAD
      - Suman373
=======
      - suman373
>>>>>>> 350310163d4012edafe35ba605a67c98a01052b7
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Other Changes
      labels:
<<<<<<< HEAD
        - "*"
=======
        - "*"
>>>>>>> 350310163d4012edafe35ba605a67c98a01052b7
